source 'https://rubygems.org'
gem 'sinatra'
gem 'sinatra-contrib'
gem 'puma'
gem 'require_all'
gem 'rake'
gem 'pg'
gem 'activerecord'
gem 'sinatra-activerecord'
gem 'pry'
gem 'faker'
# gem bcrypt hash password
gem 'bcrypt'
# gem flash push message
gem 'sinatra-flash'
